//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.10 at 07:10:21 PM CEST 
//


package cocome.cloud.sa.serviceprovider;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ServiceProviderObjectFactory {
	
	private final static QName _ServiceProviderCatalog_QNAME = new QName("", "ServiceProviderCatalog");
	private final static QName _ServiceProvider_QNAME = new QName("", "ServiceProvider");
	private final static QName _Service_QNAME = new QName("", "Service");


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ServiceProviderObjectFactory() {}

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link ServiceProvider }
     * 
     */
    public ServiceProvider createServiceProvider() {
        return new ServiceProvider();
    }
    
    /**
     * Create an instance of {@link ServiceProviderCatalog }
     * 
     */
    public ServiceProviderCatalog createServiceProviderCatalog() {
        return new ServiceProviderCatalog();
    }
    
    @XmlElementDecl(namespace = "", name = "ServiceProviderCatalog")
    public JAXBElement<ServiceProviderCatalog> createServiceProvider(ServiceProviderCatalog value) {
        return new JAXBElement<ServiceProviderCatalog>(_ServiceProviderCatalog_QNAME, ServiceProviderCatalog.class, null, value);
    }
    
    @XmlElementDecl(namespace = "", name = "ServiceProvider")
    public JAXBElement<ServiceProvider> createServiceProvider(ServiceProvider value) {
        return new JAXBElement<ServiceProvider>(_ServiceProvider_QNAME, ServiceProvider.class, null, value);
    }
    
    @XmlElementDecl(namespace = "", name = "Service")
    public JAXBElement<Service> createService(Service value) {
    	return new JAXBElement<Service>(_Service_QNAME, Service.class, null, value);
    }

}
